kind: Deployment
apiVersion: apps/v1
metadata:
  name: dockerimage-canary
spec:
  replicas:
  template:
    metadata:
      name: dockerimage
      labels:
        app: dockerimage
        env: canary
    spec:
      containers:
      - name: dockerimage
        image: acrdemo66.azurecr.io/dockerimage:v1.0
        resources:
          limits:
            memory: "300Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
      imagePullSecrets:
      - name: secret
