kind: Deployment
apiVersion: apps/v1
metadata:
  name: dockerimage
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dockerimage
  template:
    metadata:
      name: dockerimage
      labels:
        app: dockerimage
        env: production
    spec:
      containers:
      - name: dockerimage
        image: acrdemo66.azurecr.io/dockerimage:v1.0
      imagePullSecrets:
      - name: secret
